# Generated by Django 4.0.4 on 2022-05-29 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('benefit_percentage', models.IntegerField()),
                ('benefit_type', models.CharField(choices=[('cashback', 'Cashback'), ('voucher', 'Voucher')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('number', 'Number'), ('time', 'Time')], max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('num', models.IntegerField(null=True)),
                ('benefit', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposited_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('started_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_goals', to='plans.benefit')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_goals', to='plans.plan')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_goals', to='plans.promotion')),
            ],
        ),
    ]
